version: "3"
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=dev
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_CONN_STR=postgres://dev@db:5432/dev?sslmode=disable
