version: "3"
services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=dev
  api:
    build: .
    links:
      - db
    ports:
      - 8080:8080
